name: Connect to Netbird
on:
  push:
    branches:
      - main

jobs:
  netbird:
    name: Connect to Netbird
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Netbird Connect
        id: netbird
        uses: Alemiz112/netbird-connect@v1
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}
          hostname: 'my-custom-hostname'
          management-url: 'https://my-netbird-management-url.com'
          args: '--custom-arg value'